### ISSUE TITLE
Common API format definition

### ISSUE THREAD

**Issue by IvanDelsinne** [IvanDelsinne/sinking#16]
Ideally, what I'd like to have is the following:

```
- /s/ -> Sink list, with place for additional data
- /s/:sink -> Payload for the given sink (with additional data)
- /batch/sink1,sink2,sink3 -> like `/:sink`, but enclosed in an object with the sink id as key, and the corresponding payload as value
```

Putting sinks access on a subroute allows to avoid conflicts, and to allow for potential extensions, such as health reports.

## General format

Every API route would follow the following format:

```json
{
	"success": true,
	"error": null,
	"data": {}
}
```

- `success` is a boolean, at true if nothing happened
- `error` is an optional string: if no error happened (`success == true`), then it contains `null` (explicitly, the key is set and the value is `null`).
- `data` is the data payload as described by the API-specific section

## `/s/`: Sink list

Will return a reponse of the following format:

```json
{
	"count": 1,
	"sinks": [
		"keys"
	]
}
```

- `count`: the found sinks count
- `sinks`: the sink IDs

## `/s/:sink`: Specific sink data

Will return a sink-specific payload.

```json
{
	"last_collected": "ISO8601-formatted TS",
	"value": null
}
```

- `last_collected` is the timestamp of the last time at which the sink value was edited
- `value` is the value returned by the collector's `invoke()` method

## `/batch/IDs`: Batch of sink data

Will return the same payload as [Sink-specific data](#), enclosed in a key-value pair.
Additionally, it'll return a list of every nonexistent sink key.

`IDs` is expected to follow the following format: `ID(,ID)*`, where `ID` is the sink ID format.

```json
{
	"total_count": 1,
	"success": {
		"datetime": {}
	},
	"failure": {
		"nonexistent-sink": "error_msg"
	}
}
```

- `total_count`: the total number of returned sinks (combining success and failure)
- `success`: Key-value-defined list of sinks and their payload (as defined in [Sink-specific data](#))
- `failure`: Key-value-defined list of sinks and their associated encountered errors
    The value of each erroneous sink is following the usual error format (`ID:message`)

# Potential errors

There are a few errors to consider, when dealing with sink-specific and batch requests.

Those errors will use the following format.

```
ID:message
/[\d]+:.+/
```

This format will *always* be used, it is thus safe to assume that every error message is following this format.

## General errors: Global code `0x`

- `01`: Internal or unknown error

## Sink-specific request: Global code `1x`

- `11`: No sink found with this ID

- `HTTP 400`: The sink ID doesn't follow the expected format (no body to be expected)

## Batch request: Global code `2x`

- `21`: No sink found with those IDs (at all, returning an empty list for success)

- `HTTP 400`: The batch request value doesn't follow the expected format (no body to be expected)

## Additional info.

- The API is purely read-only, and will *never* trigger a collector. It only sources its data from the Redis database.

## Edits

- Renamed `last_edited` to `last_collected`, still thinking about how to properly handle errors.
- Specified error format definition, changed batch API URL, request format, and result payload.

**Comment by MarlBurroW** [comment]
Looks good to me, just few things:

`last_edited` key is ambiguous with this name because it assumes that we can edit the value. `last_collected` sounds better to me. 

Are you sure that a single `error` root key is enough to handle batch errors ?  You should consider to use an additional `errors` or a `sink_errors` key that will be an object indexed by sink name and valued with a sink specific errors. By this way the `not_found` key can be removed (because placed in the new `sink_errors` props).

**Comment by MarlBurroW** [comment]
@IvanDelsinne The last response format looks OK for me.
